add_newline = true

##########################

## iceburg + sakana

##########################

[character]
success_symbol = "[>](bold #84a0c6)[Îµ](bold #b4be82)[Îµ](bold #e2a478)[Îµ](bold #a093c7)[ ï¾Ÿ>](bold #89b8c2) "
error_symbol = "ğŸ¥º"

[directory]
truncation_length = 100
truncate_to_repo = false
style = "#84a0c6"
home_symbol = "ã€œ"

##########################

## forest

##########################

# [character]
# success_symbol = "[ğŸ¦Š â‡’](bold #93dec0) "
# error_symbol = "ğŸ¥º"
# use_symbol_for_status = true

# [directory]
# truncation_length = 100
# truncate_to_repo = false
# style = "#bbed84"
# home_symbol = "ã€œ"

# [nodejs]
# style = "#93dec0"

##########################

## menhera

##########################

# [character]
# success_symbol = "[>](bold #ba55d3)[>](bold #dda0dd)[>](bold #ffc0cb) "
# error_symbol = "ğŸ¥º"
# use_symbol_for_status = true

# [directory]
# truncation_length = 100
# truncate_to_repo = false
# style = "#ba55d3"
# home_symbol = "ã€œ"

# [nodejs]
# style = "#b3fdb9"

# [package]
# style = "#ffc0cb"
# symbol = "ğŸ "

##########################

[memory_usage]
disabled = true

[git_branch]
style = "#dda0dd"
symbol = "â™¥:\uf113 "
truncation_length = 20
truncation_symbol = ""

[git_commit]
commit_hash_length = 30

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ pick "

[git_status]
conflicted = "ã€conflicted!!!ã€‘ğŸ³ "
ahead = "ã€aheadã€‘ğŸ ğŸ’¨ comitãŒå…ˆè¡Œã—ã¦ã‚‹ã‚ˆ "
behind = "ã€behindã€‘ğŸ˜° pullã§ãã¦ãªã„ã‚ˆ "
diverged = "ã€divergedã€‘ğŸ˜µ ã“ã‚“ãŒã‚‰ãŒã£ãŸ "
untracked = "ã€untrackedã€‘ğŸŒšâ€ æœªè¿½è·¡ "
stashed = "ã€stashedã€‘ğŸ“¦ å¤‰æ›´ã‚’é€€é¿ "
modified = "ã€modifiedã€‘ğŸ“ å¤‰æ›´æ¸ˆã¿ "
staged = "ã€stagedã€‘ğŸ”¦ ã‚¹ãƒ†ãƒ¼ã‚¸ãƒ³ã‚° "
renamed = "ã€renamedã€‘ğŸ· "
deleted = "ã€deletedã€‘ğŸ—‘ "

[battery.display]
threshold = 100
style = "bold blue"

[battery]
full_symbol = "ğŸ¤—"
charging_symbol = "ğŸ˜Œ"
discharging_symbol = "ğŸ˜¨"