add_newline = true

##########################

## iceburg + sakana

##########################

# [character]
# format = "[>](bold #84a0c6)[Îµ](bold #b4be82)[Îµ](bold #e2a478)[Îµ](bold #a093c7)[ ï¾Ÿ>](bold #89b8c2) "
# success_symbol = "[>](bold #89b8c2) "
# error_symbol = "ğŸ¥º"

# [directory]
# truncation_length = 100
# truncate_to_repo = false
# style = "#84a0c6"
# home_symbol = "ã€œ"

##########################

## menhera

##########################

[character]
format = "[> ](bold #dda0dd)"
style_success = "#ff69b4"
symbol = "âœ"
error_symbol = "âœ—"
use_symbol_for_status = true

[directory]
truncation_length = 100
truncate_to_repo = false
style = "#ba55d3"
home_symbol = "ã€œ"

[nodejs]
style = "#ffc0cb"

[package]
style = "#ffc0cb"
symbol = "ï£– "

##########################

[memory_usage]
disabled = true

[git_branch]
style = "#dda0dd"
symbol = "â™¥:\uf113 "
truncation_length = 20
truncation_symbol = ""

[git_commit]
commit_hash_length = 30

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ³ "
ahead = "ğŸ ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·<200d>"
modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ "